import {useEffect,useState} from 'react';
const box={background:'#1e2433',border:'1px solid #2d3748',borderRadius:8,padding:16};
const input={background:'#0f172a',color:'#e2e8f0',border:'1px solid #334155',borderRadius:4,padding:'7px 9px'};
const label={display:'flex',flexDirection:'column',gap:4,color:'#cbd5e1',fontSize:12,fontWeight:600};
const hint={color:'#64748b',fontSize:11,fontWeight:400,maxWidth:190,lineHeight:1.35};
export default function Inventory(){const [rolls,setRolls]=useState([]),[summary,setSummary]=useState([]),[printers,setPrinters]=useState([]),[types,setTypes]=useState([]),[colors,setColors]=useState([]),[filterType,setFilterType]=useState(''),[filterColor,setFilterColor]=useState(''),[viewMode,setViewMode]=useState('cards'),[form,setForm]=useState({name:'',filament_type_id:'',filament_color_id:'',initial_weight_g:1000,purchase_price:0,location:''});
 const load=()=>Promise.all([fetch('/api/inventory').then(r=>r.json()),fetch('/api/inventory/summary').then(r=>r.json()),fetch('/api/printers').then(r=>r.json()),fetch('/api/filaments/types').then(r=>r.json()),fetch('/api/filaments/colors').then(r=>r.json())]).then(([a,b,c,d,e])=>{setRolls(a);setSummary(b);setPrinters(c);setTypes(d);setColors(e)});useEffect(()=>{load()},[]);
 const add=async()=>{const r=await fetch('/api/inventory',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});if(r.ok){const result=await r.json();setForm({...form,name:''});await load();if(result.restocked)alert(`${result.added_weight_g} g wurden dem vorhandenen Bestand hinzugefügt.`)}else alert((await r.json()).error)};
 const adjust=async r=>{const v=prompt(`Neues verbleibendes Nettogewicht für ${r.name} in Gramm`,r.remaining_weight_g);if(v==null)return;const note=prompt('Grund für die Korrektur','Rolle manuell gewogen');await fetch(`/api/inventory/${r.id}/adjust`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({remaining_weight_g:Number(v),note})});load()};
 const assign=async(r,e)=>{if(!e.target.value){await fetch(`/api/inventory/${r.id}/assign`,{method:'DELETE'});return load()}const [printer_id,slot]=e.target.value.split(':');await fetch(`/api/inventory/${r.id}/assign`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({printer_id:Number(printer_id),slot:Number(slot)})});load()};
 const colorNames=[...new Set(colors.filter(c=>!filterType||String(c.type_id)===filterType).map(c=>c.name))].sort((a,b)=>a.localeCompare(b));
 const matches=x=>(!filterType||String(x.filament_type_id)===filterType)&&(!filterColor||x.color===filterColor);
 const filteredSummary=summary.filter(matches),filteredRolls=rolls.filter(matches);
 const resetFilters=()=>{setFilterType('');setFilterColor('')};
 const addForMaterial=s=>{const existing=rolls.find(r=>Number(r.filament_color_id)===Number(s.filament_color_id));setForm({...form,name:existing?.name||`${s.material} ${s.color}`,filament_type_id:String(s.filament_type_id),filament_color_id:String(s.filament_color_id)});document.getElementById('new-roll-form')?.scrollIntoView({behavior:'smooth',block:'start'})};
 const removeForMaterial=async s=>{const candidates=rolls.filter(r=>Number(r.filament_color_id)===Number(s.filament_color_id)&&Number(r.roll_count||0)>0);if(!candidates.length)return;let selected=candidates[0];if(candidates.length>1){const names=candidates.map(r=>r.name).join(', ');const chosen=prompt(`Aus welcher Lagerposition soll eine Rolle entfernt werden?\n${names}`,selected.name);if(chosen==null)return;selected=candidates.find(r=>r.name.toLowerCase()===chosen.trim().toLowerCase());if(!selected){alert('Bezeichnung nicht gefunden.');return}}const defaultWeight=Number(selected.roll_count||1)===1?Number(selected.remaining_weight_g):Number(selected.remaining_weight_g)/Number(selected.roll_count);const weight=prompt(`Verbleibendes Nettogewicht der entfernten Rolle in Gramm`,defaultWeight.toFixed(1));if(weight==null)return;const response=await fetch(`/api/inventory/${selected.id}/remove-roll`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({remaining_weight_g:Number(weight),note:`Rolle ${s.material} ${s.color} entfernt`})});if(!response.ok)return alert((await response.json()).error);load()};
 const slotOptions=printers.flatMap(p=>Array.from({length:p.type==='bambu'?16:1},(_,slot)=><option key={`${p.id}:${slot}`} value={`${p.id}:${slot}`}>{p.name} · Slot {slot}</option>));
 const th={textAlign:'left',padding:'9px 10px',fontSize:12,color:'#94a3b8',borderBottom:'1px solid #334155',whiteSpace:'nowrap'};
 const td={padding:'9px 10px',borderBottom:'1px solid #293243',fontSize:13,verticalAlign:'middle'};
 return <div><h1>Filamentinventar</h1><p style={{color:'#94a3b8'}}>Rollenbestand, Druckerzuordnung und automatische Verbrauchsbuchung abgeschlossener Druckjobs.</p>
 <div id="new-roll-form" style={{...box,marginBottom:18,scrollMarginTop:16}}>
  <h2 style={{fontSize:15,margin:'0 0 14px'}}>Neue Filamentrolle</h2>
  <div style={{display:'flex',gap:14,flexWrap:'wrap',alignItems:'flex-end'}}>
   <label style={label}>Bezeichnung *<input style={input} type="text" placeholder="z. B. PLA Schwarz" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><span style={hint}>Eindeutiger Lagername. Bei Wiederverwendung wird das Gewicht zum vorhandenen Bestand addiert.</span></label>
   <label style={label}>Materialtyp *<select style={{...input,minWidth:170}} value={form.filament_type_id} onChange={e=>setForm({...form,filament_type_id:e.target.value,filament_color_id:''})}><option value="">Bitte auswählen</option>{types.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select><span style={hint}>Wird in Settings → Filament Library gepflegt</span></label>
   <label style={label}>Material / Farbe *<select style={{...input,minWidth:190}} value={form.filament_color_id} disabled={!form.filament_type_id} onChange={e=>setForm({...form,filament_color_id:e.target.value})}><option value="">Bitte auswählen</option>{colors.filter(c=>String(c.type_id)===String(form.filament_type_id)).map(c=><option key={c.id} value={c.id}>{c.name}{c.hex_color?` · ${c.hex_color}`:''}</option>)}</select><span style={hint}>{form.filament_type_id?'Nur Materialien des gewählten Typs':'Zuerst Materialtyp auswählen'}</span></label>
   <label style={label}>Filament-Nettogewicht *<div style={{display:'flex',alignItems:'center',gap:6}}><input style={{...input,width:110}} type="number" min="1" step="1" value={form.initial_weight_g} onChange={e=>setForm({...form,initial_weight_g:e.target.value})}/><span>g</span></div><span style={hint}>Nur das Filament, ohne Leergewicht der Spule</span></label>
   <label style={label}>Kaufpreis der Rolle<div style={{display:'flex',alignItems:'center',gap:6}}><input style={{...input,width:110}} type="number" min="0" step="0.01" value={form.purchase_price} onChange={e=>setForm({...form,purchase_price:e.target.value})}/><span>€</span></div><span style={hint}>Gesamtpreis der vollen Rolle, nicht Preis pro kg</span></label>
   <label style={label}>Lagerort<input style={input} type="text" placeholder="z. B. Regal A2" value={form.location} onChange={e=>setForm({...form,location:e.target.value})}/><span style={hint}>Optional</span></label>
   <button onClick={add} disabled={!form.name.trim()||!form.filament_type_id||!form.filament_color_id} style={{marginBottom:18,opacity:(!form.name.trim()||!form.filament_type_id||!form.filament_color_id)?.5:1}}>Rolle anlegen</button>
  </div>
 </div>
 <div style={{...box,display:'flex',gap:14,alignItems:'flex-end',flexWrap:'wrap',marginBottom:20}}>
  <label style={label}>Materialtyp<select style={{...input,minWidth:170}} value={filterType} onChange={e=>{setFilterType(e.target.value);setFilterColor('')}}><option value="">Alle Materialtypen</option>{types.map(t=><option key={t.id} value={String(t.id)}>{t.name}</option>)}</select></label>
  <label style={label}>Farbe<select style={{...input,minWidth:170}} value={filterColor} onChange={e=>setFilterColor(e.target.value)}><option value="">Alle Farben</option>{colorNames.map(name=><option key={name} value={name}>{name}</option>)}</select></label>
  {(filterType||filterColor)&&<button onClick={resetFilters}>Filter zurücksetzen</button>}
  <span style={{color:'#64748b',fontSize:12,marginBottom:8}}>{filteredRolls.length} von {rolls.length} Lagerpositionen</span>
  <div style={{display:'flex',marginLeft:'auto',border:'1px solid #334155',borderRadius:6,overflow:'hidden'}}><button onClick={()=>setViewMode('cards')} style={{border:0,borderRadius:0,background:viewMode==='cards'?'#1d4ed8':'#0f172a',color:'#fff'}}>▦ Kacheln</button><button onClick={()=>setViewMode('table')} style={{border:0,borderRadius:0,background:viewMode==='table'?'#1d4ed8':'#0f172a',color:'#fff'}}>☷ Tabelle</button></div>
 </div>

 <h2 style={{fontSize:16,margin:'22px 0 10px'}}>Materialbestand gesamt</h2>
 {filteredSummary.length===0&&<div style={{...box,color:'#64748b',marginBottom:24}}>Keine Materialien entsprechen dem gewählten Filter.</div>}
 {viewMode==='cards'&&<div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(220px,1fr))',gap:10,marginBottom:24}}>{filteredSummary.map(s=><div key={s.filament_color_id} style={box}><div style={{display:'flex',alignItems:'center',gap:8}}>{s.hex_color&&<span style={{width:14,height:14,borderRadius:'50%',background:s.hex_color,border:'1px solid #64748b'}}/>}<strong>{s.material} · {s.color}</strong><span style={{marginLeft:'auto',display:'flex',gap:5}}><button title="Rolle hinzufügen" aria-label={`Rolle ${s.material} ${s.color} hinzufügen`} onClick={()=>addForMaterial(s)} style={{fontSize:18,padding:'1px 8px',background:'#166534',color:'#fff'}}>+</button><button title="Rolle entfernen" aria-label={`Rolle ${s.material} ${s.color} entfernen`} disabled={!Number(s.roll_count)} onClick={()=>removeForMaterial(s)} style={{fontSize:18,padding:'1px 9px',background:'#991b1b',color:'#fff',opacity:Number(s.roll_count)?1:.4}}>−</button></span></div><div style={{fontSize:24,fontWeight:700,marginTop:10}}>{Number(s.remaining_weight_g).toFixed(1)} g</div><div style={{color:'#94a3b8',fontSize:12}}>{Number(s.roll_count)} {Number(s.roll_count)===1?'Rolle':'Rollen'} · Bestandswert {Number(s.remaining_value).toFixed(2)} €</div></div>)}</div>}
 {viewMode==='table'&&filteredSummary.length>0&&<div style={{...box,padding:0,overflowX:'auto',marginBottom:24}}><table style={{width:'100%',borderCollapse:'collapse'}}><thead><tr><th style={th}>Materialtyp</th><th style={th}>Farbe</th><th style={th}>Rollen</th><th style={th}>Verfügbares Gewicht</th><th style={th}>Bestandswert</th><th style={th}>Rollenbestand</th></tr></thead><tbody>{filteredSummary.map(s=><tr key={s.filament_color_id}><td style={td}><strong>{s.material}</strong></td><td style={td}><span style={{display:'inline-flex',alignItems:'center',gap:7}}>{s.hex_color&&<span style={{width:12,height:12,borderRadius:'50%',background:s.hex_color,border:'1px solid #64748b'}}/>}{s.color}</span></td><td style={td}>{Number(s.roll_count)}</td><td style={td}><strong>{Number(s.remaining_weight_g).toFixed(1)} g</strong></td><td style={td}>{Number(s.remaining_value).toFixed(2)} €</td><td style={td}><span style={{display:'flex',gap:5}}><button title="Rolle hinzufügen" onClick={()=>addForMaterial(s)} style={{fontSize:17,background:'#166534',color:'#fff'}}>+</button><button title="Rolle entfernen" disabled={!Number(s.roll_count)} onClick={()=>removeForMaterial(s)} style={{fontSize:17,background:'#991b1b',color:'#fff',opacity:Number(s.roll_count)?1:.4}}>−</button></span></td></tr>)}</tbody></table></div>}

 <h2 style={{fontSize:16,margin:'0 0 10px'}}>Lagerpositionen</h2>
 {filteredRolls.length===0&&<div style={{...box,color:'#64748b'}}>Keine Lagerpositionen entsprechen dem gewählten Filter.</div>}
 {viewMode==='cards'&&<div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(300px,1fr))',gap:12}}>{filteredRolls.map(r=>{const pct=Math.max(0,Math.round(r.remaining_weight_g/r.initial_weight_g*100));return <div style={box} key={r.id}><div style={{display:'flex',justifyContent:'space-between'}}><strong>{r.name}</strong><span>{r.material} · {r.color||'keine Farbe'}</span></div><div style={{height:8,background:'#0f172a',margin:'12px 0',borderRadius:4}}><div style={{height:8,width:`${pct}%`,background:pct<15?'#ef4444':'#22c55e',borderRadius:4}}/></div><div><strong>{Number(r.remaining_weight_g).toFixed(1)} g</strong> verbleibend von {Number(r.initial_weight_g).toFixed(0)} g · {pct}%</div><div style={{color:'#64748b',fontSize:12,margin:'5px 0'}}>{Number(r.roll_count||1)} {Number(r.roll_count||1)===1?'Rolle':'Rollen'} · {r.location||'Kein Lagerort'} · Einkaufswert {Number(r.purchase_price).toFixed(2)} €</div><label style={{...label,marginTop:10}}>Geladen in<select style={{...input,width:'100%'}} value={r.printer_id?`${r.printer_id}:${r.slot}`:''} onChange={e=>assign(r,e)}><option value="">Nicht geladen</option>{slotOptions}</select></label><button style={{marginTop:8}} onClick={()=>adjust(r)}>Gewicht korrigieren</button></div>})}</div>}
 {viewMode==='table'&&filteredRolls.length>0&&<div style={{...box,padding:0,overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse'}}><thead><tr><th style={th}>Bezeichnung</th><th style={th}>Material</th><th style={th}>Rollen</th><th style={th}>Restgewicht</th><th style={th}>Lagerort</th><th style={th}>Einkaufswert</th><th style={th}>Geladen in</th><th style={th}></th></tr></thead><tbody>{filteredRolls.map(r=><tr key={r.id}><td style={td}><strong>{r.name}</strong></td><td style={td}>{r.material} · {r.color}</td><td style={td}>{Number(r.roll_count||1)}</td><td style={td}><strong>{Number(r.remaining_weight_g).toFixed(1)} g</strong></td><td style={td}>{r.location||'—'}</td><td style={td}>{Number(r.purchase_price).toFixed(2)} €</td><td style={td}><select style={{...input,minWidth:150}} value={r.printer_id?`${r.printer_id}:${r.slot}`:''} onChange={e=>assign(r,e)}><option value="">Nicht geladen</option>{slotOptions}</select></td><td style={td}><button onClick={()=>adjust(r)}>Korrigieren</button></td></tr>)}</tbody></table></div>}
 </div>}
