import {useEffect,useState} from 'react';
const box={background:'#1e2433',border:'1px solid #2d3748',borderRadius:8,padding:16};const input={background:'#0f172a',color:'#e2e8f0',border:'1px solid #334155',borderRadius:4,padding:'7px 9px'};
export default function Maintenance(){const [plans,setPlans]=useState([]),[history,setHistory]=useState([]),[printers,setPrinters]=useState([]),[f,setF]=useState({printer_id:'',name:'',interval_days:'',interval_print_hours:''});
 const load=()=>Promise.all([fetch('/api/maintenance').then(r=>r.json()),fetch('/api/maintenance/history/all').then(r=>r.json()),fetch('/api/printers').then(r=>r.json())]).then(([a,b,c])=>{setPlans(a);setHistory(b);setPrinters(c)});useEffect(()=>{load()},[]);
 const add=async()=>{const r=await fetch('/api/maintenance',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(f)});if(r.ok){setF({...f,name:''});load()}else alert((await r.json()).error)};
 const done=async p=>{const notes=prompt(`Work performed: ${p.name}`,'Completed');if(notes==null)return;const cost=prompt('Maintenance cost (€)','0');await fetch(`/api/maintenance/${p.id}/complete`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({notes,cost:Number(cost||0)})});load()};
 return <div><h1>Maintenance</h1><p style={{color:'#94a3b8'}}>Calendar- and print-hour-based service plans with machine history.</p><div style={{...box,display:'flex',gap:8,flexWrap:'wrap',marginBottom:18}}><select style={input} value={f.printer_id} onChange={e=>setF({...f,printer_id:e.target.value})}><option value="">Printer</option>{printers.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select><input style={input} placeholder="Task" value={f.name} onChange={e=>setF({...f,name:e.target.value})}/><input style={input} type="number" placeholder="Every N days" value={f.interval_days} onChange={e=>setF({...f,interval_days:e.target.value})}/><input style={input} type="number" placeholder="Every N print hours" value={f.interval_print_hours} onChange={e=>setF({...f,interval_print_hours:e.target.value})}/><button onClick={add}>Add plan</button></div>
 <h2>Plans</h2><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(280px,1fr))',gap:10}}>{plans.filter(p=>p.is_active).map(p=><div key={p.id} style={{...box,borderColor:p.is_due?'#ef4444':'#2d3748'}}><strong>{p.printer_name} · {p.name}</strong><div style={{margin:'8px 0',color:p.is_due?'#f87171':'#94a3b8'}}>{p.is_due?'Due now':'On schedule'}</div><div style={{fontSize:12,color:'#64748b'}}>{Number(p.current_print_hours).toFixed(1)} print hours{p.due_print_hours!=null?` · due at ${Number(p.due_print_hours).toFixed(1)} h`:''}{p.due_at?` · ${new Date(p.due_at).toLocaleDateString()}`:''}</div><button style={{marginTop:10}} onClick={()=>done(p)}>Mark completed</button></div>)}</div>
 <h2 style={{marginTop:24}}>History</h2><div style={box}>{history.length===0?'No maintenance recorded.':history.map(h=><div key={h.id} style={{padding:'8px 0',borderBottom:'1px solid #2d3748'}}><strong>{h.printer_name}</strong> · {h.plan_name||'Maintenance'} · {new Date(h.performed_at).toLocaleString()} · €{Number(h.cost).toFixed(2)}<div style={{color:'#64748b',fontSize:12}}>{h.notes}</div></div>)}</div></div>}
